package relay

import (
	"embed"
	"io/fs"
)

//go:embed all:web-dist
var embeddedWeb embed.FS

// EmbeddedWebFS returns the relay-bundled static web assets rooted at
// the repository's Vite build output. Contents are regenerated by
// scripts/build-web.sh from web/dist/; CI's drift gate (git diff
// --exit-code) catches forgotten syncs.
func EmbeddedWebFS() fs.FS {
	sub, err := fs.Sub(embeddedWeb, "web-dist")
	if err != nil {
		// fs.Sub only errors on a malformed name; "web-dist" is a constant.
		panic(err)
	}
	return sub
}
