# syntax=docker/dockerfile:1

FROM golang:1.23-bookworm AS build

ARG TARGETOS
ARG TARGETARCH
ARG GOPROXY=https://proxy.golang.org,direct

WORKDIR /src

COPY go.mod go.sum ./
RUN GOPROXY=${GOPROXY} go mod download

COPY cmd/atterm-rendezvous ./cmd/atterm-rendezvous
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build \
    -trimpath \
    -buildvcs=false \
    -ldflags="-s -w" \
    -o /out/atterm-rendezvous \
    ./cmd/atterm-rendezvous

FROM alpine:3.20

RUN addgroup -S -g 10001 atterm \
 && adduser -S -D -H -u 10001 -G atterm atterm

COPY --from=build /out/atterm-rendezvous /usr/local/bin/atterm-rendezvous

USER atterm
EXPOSE 8443

ENTRYPOINT ["/usr/local/bin/atterm-rendezvous"]
CMD ["--addr", ":8443"]
