package agent

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"log"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/attson/atterm/internal/proto"
	"github.com/google/uuid"
	"nhooyr.io/websocket"
)

// Options configures the relay client.
type Options struct {
	RelayURL  string // ws://host:port (with or without trailing slash)
	Token     string
	SessionID uuid.UUID // generated by caller; reused on reconnect
	Command   string    // human-readable label
	HostID    string    // stable machine UUID
	Host      string    // hostname of this machine
	User      string    // OS username on this machine
}

// Client links a Pty to a relay over WebSocket. The Pty is owned by the caller;
// Run blocks until ctx is cancelled or the child exits.
type Client struct {
	opts Options
	pty  *Pty

	seqMu sync.Mutex
	seq   uint64

	stdinFromRelay chan []byte
	resizeReq      chan [2]uint16
	localResize    chan [2]uint16

	ptyExit  atomic.Bool
	exitCode atomic.Int32
}

// NewClient builds a Client. SessionID must be set; OPEN reuses it on reconnect.
func NewClient(opts Options, p *Pty) *Client {
	c := &Client{
		opts:           opts,
		pty:            p,
		stdinFromRelay: make(chan []byte, 64),
		resizeReq:      make(chan [2]uint16, 8),
		localResize:    make(chan [2]uint16, 8),
	}
	p.OnResize(func(cols, rows uint16) {
		select {
		case c.localResize <- [2]uint16{cols, rows}:
		default:
		}
	})
	return c
}

func (c *Client) nextSeq() uint64 {
	c.seqMu.Lock()
	defer c.seqMu.Unlock()
	c.seq++
	return c.seq
}

// MarkExit tells Run that the child has exited and the loop should not reconnect.
// The exit code is included in the final CLOSE frame.
func (c *Client) MarkExit(code int) {
	c.exitCode.Store(int32(code))
	c.ptyExit.Store(true)
}

// Run executes the agent loop: maintain a connection, push PTY output, pull
// IN/RESIZE frames, and reconnect on transient failures. Returns nil after a
// clean shutdown via MarkExit + ctx cancel.
func (c *Client) Run(ctx context.Context) error {
	ptyOut := make(chan []byte, 256)
	go c.readPty(ptyOut)
	go c.writePty(ctx)

	backoff := 500 * time.Millisecond
	for {
		if ctx.Err() != nil {
			return nil
		}
		err := c.runOnce(ctx, ptyOut)
		if c.ptyExit.Load() {
			return nil
		}
		if errors.Is(err, ctx.Err()) {
			return nil
		}
		if err != nil {
			log.Printf("agent: relay connection lost: %v (reconnect in %s)", err, backoff)
		}
		select {
		case <-ctx.Done():
			return nil
		case <-time.After(backoff):
		}
		backoff *= 2
		if backoff > 8*time.Second {
			backoff = 8 * time.Second
		}
	}
}

func (c *Client) readPty(out chan<- []byte) {
	r := c.pty.PipeLocal()
	for {
		buf := make([]byte, 4096)
		n, err := r.Read(buf)
		if n > 0 {
			out <- buf[:n]
		}
		if err != nil {
			if err != io.EOF && !strings.Contains(err.Error(), "input/output error") {
				log.Printf("agent: pty read: %v", err)
			}
			close(out)
			return
		}
	}
}

func (c *Client) writePty(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			return
		case data, ok := <-c.stdinFromRelay:
			if !ok {
				return
			}
			if _, err := c.pty.File().Write(data); err != nil {
				return
			}
		case sz := <-c.resizeReq:
			_ = c.pty.Resize(sz[0], sz[1])
		}
	}
}

func (c *Client) dial(ctx context.Context) (*websocket.Conn, error) {
	dialCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	hdr := map[string][]string{}
	if c.opts.Token != "" {
		hdr["Authorization"] = []string{"Bearer " + c.opts.Token}
	}
	wsURL := strings.TrimRight(c.opts.RelayURL, "/")
	conn, _, err := websocket.Dial(dialCtx, wsURL+"/agent", &websocket.DialOptions{HTTPHeader: hdr})
	if err != nil {
		return nil, err
	}
	conn.SetReadLimit(1 * 1024 * 1024)
	return conn, nil
}

func (c *Client) sendOpen(ctx context.Context, conn *websocket.Conn) error {
	cols, rows, _ := c.pty.Size()
	if cols == 0 {
		cols, rows = 80, 24
	}
	cwd, _ := os.Getwd()
	openPayload, _ := json.Marshal(proto.OpenPayload{
		Cols:    cols,
		Rows:    rows,
		Command: c.opts.Command,
		Cwd:     cwd,
		Title:   c.opts.Command,
		HostID:  c.opts.HostID,
		Host:    c.opts.Host,
		User:    c.opts.User,
	})
	wctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	return conn.Write(wctx, websocket.MessageBinary, proto.Marshal(proto.Frame{
		Type:      proto.TypeOpen,
		SessionID: c.opts.SessionID,
		Payload:   openPayload,
	}))
}

func (c *Client) sendClose(ctx context.Context, conn *websocket.Conn, code int) {
	payload, _ := json.Marshal(proto.ClosePayload{ExitCode: code})
	wctx, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	_ = conn.Write(wctx, websocket.MessageBinary, proto.Marshal(proto.Frame{
		Type:      proto.TypeClose,
		SessionID: c.opts.SessionID,
		Payload:   payload,
	}))
}

func (c *Client) runOnce(ctx context.Context, ptyOut <-chan []byte) error {
	conn, err := c.dial(ctx)
	if err != nil {
		return err
	}
	defer conn.Close(websocket.StatusNormalClosure, "")

	if err := c.sendOpen(ctx, conn); err != nil {
		return err
	}

	connCtx, cancel := context.WithCancel(ctx)
	defer cancel()
	errCh := make(chan error, 2)

	// Reader: pull IN/RESIZE/PING from relay.
	go func() {
		for {
			mt, data, err := conn.Read(connCtx)
			if err != nil {
				errCh <- err
				return
			}
			if mt != websocket.MessageBinary {
				continue
			}
			f, err := proto.Unmarshal(data)
			if err != nil {
				continue
			}
			switch f.Type {
			case proto.TypeIn:
				select {
				case c.stdinFromRelay <- f.Payload:
				case <-connCtx.Done():
					return
				}
			case proto.TypeResize:
				if cols, rows, err := proto.DecodeResize(f.Payload); err == nil {
					select {
					case c.resizeReq <- [2]uint16{cols, rows}:
					default:
					}
				}
			case proto.TypePing:
				wctx, wc := context.WithTimeout(connCtx, 5*time.Second)
				_ = conn.Write(wctx, websocket.MessageBinary, proto.Marshal(proto.Frame{
					Type: proto.TypePong, SessionID: c.opts.SessionID,
				}))
				wc()
			}
		}
	}()

	// Writer: ship PTY output, then on EOF send CLOSE and return.
	go func() {
		for {
			select {
			case <-connCtx.Done():
				errCh <- connCtx.Err()
				return
			case data, ok := <-ptyOut:
				if !ok {
					c.sendClose(connCtx, conn, int(c.exitCode.Load()))
					errCh <- io.EOF
					return
				}
				seq := c.nextSeq()
				wctx, wc := context.WithTimeout(connCtx, 10*time.Second)
				err := conn.Write(wctx, websocket.MessageBinary, proto.Marshal(proto.EncodeOut(c.opts.SessionID, seq, data)))
				wc()
				if err != nil {
					errCh <- err
					return
				}
			case <-c.localResize:
				// Local TTY size changed; the PTY is already resized via
				// SIGWINCH. We don't need to push RESIZE up — clients learn
				// the new size from META updates if we want; for Phase 0 this
				// is a no-op kept for the channel side effect.
			}
		}
	}()

	err = <-errCh
	cancel()
	return err
}
