// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BroadcastCommandFinished(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function CheckUpdate():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function ConfirmQuit():Promise<void>;

export function CreatePairingToken():Promise<main.PairingTokenResponse>;

export function ExportDiagnostics(arg1:string):Promise<string>;

export function FetchRelayMe():Promise<main.RelayMe>;

export function GetAutoCheckUpdates():Promise<boolean>;

export function GetClipboardPastePayload():Promise<main.ClipboardPastePayload>;

export function GetCommandNotifyThresholdSeconds():Promise<number>;

export function GetDefaultShell():Promise<string>;

export function GetDiagnostics(arg1:string):Promise<main.DiagnosticsPayload>;

export function GetEndpoint():Promise<main.Endpoint>;

export function GetHostInfo():Promise<main.HostInfo>;

export function GetLocalePreference():Promise<string>;

export function GetLogPreview():Promise<main.LogPreview>;

export function GetLoggingConfig():Promise<main.LoggingConfig>;

export function GetNotificationsEnabled():Promise<boolean>;

export function GetPluginConfig():Promise<main.PluginConfig>;

export function GetQuickTemplates():Promise<Array<main.QuickTemplate>>;

export function GetRelayConfig():Promise<main.RelayConfig>;

export function GetShellIntegrationEnabled():Promise<boolean>;

export function GetTaskPreset():Promise<string>;

export function GetTaskSidebarCollapsed():Promise<boolean>;

export function GetTerminalTheme():Promise<string>;

export function GetUpdateGHProxyURL():Promise<string>;

export function GetUpdateState():Promise<main.UpdateState>;

export function GetWebglRendererEnabled():Promise<boolean>;

export function InstallUpdate():Promise<void>;

export function ListShells():Promise<Array<string>>;

export function NewSession(arg1:main.NewSessionReq):Promise<main.NewSessionResp>;

export function PickLogFilePath():Promise<string>;

export function SetAutoCheckUpdates(arg1:boolean):Promise<void>;

export function SetCommandNotifyThresholdSeconds(arg1:number):Promise<void>;

export function SetDefaultShell(arg1:string):Promise<void>;

export function SetLocalePreference(arg1:string):Promise<void>;

export function SetLoggingConfig(arg1:main.LoggingConfig):Promise<void>;

export function SetNotificationsEnabled(arg1:boolean):Promise<void>;

export function SetPluginConfig(arg1:main.PluginConfig):Promise<void>;

export function SetQuickTemplates(arg1:Array<main.QuickTemplate>):Promise<void>;

export function SetRelayConfig(arg1:main.RelayConfig):Promise<void>;

export function SetShellIntegrationEnabled(arg1:boolean):Promise<void>;

export function MarkSessionsSeen(arg1:Array<string>,arg2:boolean):Promise<void>;

export function SetTaskPreset(arg1:string):Promise<void>;

export function SetTaskSidebarCollapsed(arg1:boolean):Promise<void>;

export function SetTerminalTheme(arg1:string):Promise<void>;

export function SetUpdateGHProxyURL(arg1:string):Promise<void>;

export function SetUplinkPaused(arg1:boolean):Promise<void>;

export function SetWebglRendererEnabled(arg1:boolean):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartDownload():Promise<void>;
