// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function GetEndpoint():Promise<main.Endpoint>;

export function GetHostInfo():Promise<main.HostInfo>;

export function GetRelayConfig():Promise<main.RelayConfig>;

export function ListShells():Promise<Array<string>>;

export function NewSession(arg1:main.NewSessionReq):Promise<main.NewSessionResp>;

export function SetRelayConfig(arg1:main.RelayConfig):Promise<void>;
