// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function GetEndpoint() {
  return window['go']['main']['App']['GetEndpoint']();
}

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetRelayConfig() {
  return window['go']['main']['App']['GetRelayConfig']();
}

export function ListShells() {
  return window['go']['main']['App']['ListShells']();
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function SetRelayConfig(arg1) {
  return window['go']['main']['App']['SetRelayConfig'](arg1);
}
