// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {hookinstall} from '../models';
import {connhealth} from '../models';
import {feishu} from '../models';

export function BeginFeishuPair():Promise<string>;

export function BroadcastCommandFinished(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function CancelDownload():Promise<void>;

export function CheckUpdate():Promise<void>;

export function ClearRelayConfig():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function ConfirmQuit():Promise<void>;

export function CreatePairingToken():Promise<main.PairingTokenResponse>;

export function DeleteFeishuBinding():Promise<void>;

export function DiscardRecoverySnapshot():Promise<void>;

export function DownloadVersion(arg1:string):Promise<void>;

export function ExportDiagnostics(arg1:string):Promise<string>;

export function FetchRelayMe():Promise<main.RelayMe>;

export function ForceRedownload(arg1:string):Promise<void>;

export function GetAINotificationsOnly():Promise<boolean>;

export function GetAccountKey():Promise<string>;

export function GetAutoCheckUpdates():Promise<boolean>;

export function GetClipboardPastePayload():Promise<main.ClipboardPastePayload>;

export function GetCommandNotifyThresholdSeconds():Promise<number>;

export function GetDefaultShell():Promise<string>;

export function GetDiagnostics(arg1:string):Promise<main.DiagnosticsPayload>;

export function GetEndpoint():Promise<main.Endpoint>;

export function GetFeishuEffectiveMode():Promise<string>;

export function GetFeishuModePref():Promise<string>;

export function GetFeishuRemoteTerminalSettings():Promise<main.FeishuRemoteTerminalSettings>;

export function GetFeishuStatus():Promise<main.FeishuStatusResp>;

export function GetHookInstallState():Promise<hookinstall.State>;

export function GetHostInfo():Promise<main.HostInfo>;

export function GetLocalePreference():Promise<string>;

export function GetLogPreview():Promise<main.LogPreview>;

export function GetLoggingConfig():Promise<main.LoggingConfig>;

export function GetNotificationsEnabled():Promise<boolean>;

export function GetPasteboardFileURLs():Promise<Array<string>>;

export function GetPinnedSessionIds():Promise<Array<string>>;

export function GetPluginConfig():Promise<main.PluginConfig>;

export function GetPtyInputDebugEnabled():Promise<boolean>;

export function GetQuickTemplates():Promise<Array<main.QuickTemplate>>;

export function GetRecoveryDialogEnabled():Promise<boolean>;

export function GetRelayConfig():Promise<main.RelayConfig>;

export function GetShellIntegrationEnabled():Promise<boolean>;

export function GetStartupError():Promise<main.StartupError>;

export function GetTaskGroupBy():Promise<string>;

export function GetTaskPreset():Promise<string>;

export function GetTaskSidebarCollapsed():Promise<boolean>;

export function GetTaskSidebarWidth():Promise<number>;

export function GetTerminalTheme():Promise<string>;

export function GetUpdateGHProxyURL():Promise<string>;

export function GetUpdateState():Promise<main.UpdateState>;

export function GetUplinkHealth():Promise<connhealth.Snapshot>;

export function GetUserHomeDir():Promise<string>;

export function GetWebglRendererEnabled():Promise<boolean>;

export function HasAccountKey():Promise<boolean>;

export function InstallUpdate():Promise<void>;

export function ListRelaySessions():Promise<Array<main.RelaySessionRow>>;

export function ListRemoteSessions():Promise<string>;

export function ListShells():Promise<Array<string>>;

export function LoadRecoverySnapshot():Promise<main.RecoverySnapshot>;

export function LoadSavedRelayPassword():Promise<string>;

export function LoginRemoteRelay(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function MarkCleanShutdown():Promise<void>;

export function MarkSessionsSeen(arg1:Array<string>,arg2:boolean):Promise<void>;

export function NewSession(arg1:main.NewSessionReq):Promise<main.NewSessionResp>;

export function PickLogFilePath():Promise<string>;

export function ProbeRelayVersion(arg1:string,arg2:boolean):Promise<void>;

export function ReceivedFilesClearAll():Promise<void>;

export function ReceivedFilesClearSession(arg1:string):Promise<void>;

export function ReceivedFilesDelete(arg1:string,arg2:string):Promise<void>;

export function ReceivedFilesList():Promise<main.ReceivedFilesSummary>;

export function ReceivedFilesOpenDir():Promise<void>;

export function RegisterRemoteRelay(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function RememberRelayPassword(arg1:string):Promise<void>;

export function RevokeRelaySession(arg1:string):Promise<void>;

export function SaveRecoverySnapshot(arg1:string):Promise<void>;

export function SendFeishuTestCard(arg1:string):Promise<void>;

export function SetAINotificationsOnly(arg1:boolean):Promise<void>;

export function SetAutoCheckUpdates(arg1:boolean):Promise<void>;

export function SetCommandNotifyThresholdSeconds(arg1:number):Promise<void>;

export function SetDefaultShell(arg1:string):Promise<void>;

export function SetFeishuCredentials(arg1:feishu.Credentials):Promise<void>;

export function SetFeishuModePref(arg1:string):Promise<void>;

export function SetFeishuRemoteTerminalSettings(arg1:boolean,arg2:string):Promise<void>;

export function SetHookInstallEnabled(arg1:boolean):Promise<void>;

export function SetLocalePreference(arg1:string):Promise<void>;

export function SetLoggingConfig(arg1:main.LoggingConfig):Promise<void>;

export function SetNotificationsEnabled(arg1:boolean):Promise<void>;

export function SetPinnedSessionIds(arg1:Array<string>):Promise<void>;

export function SetPluginConfig(arg1:main.PluginConfig):Promise<void>;

export function SetPtyInputDebugEnabled(arg1:boolean):Promise<void>;

export function SetQuickTemplates(arg1:Array<main.QuickTemplate>):Promise<void>;

export function SetRecoveryDialogEnabled(arg1:boolean):Promise<void>;

export function SetRelayConfig(arg1:main.RelayConfig):Promise<void>;

export function SetRelayDisableE2EE(arg1:boolean):Promise<void>;

export function SetShellIntegrationEnabled(arg1:boolean):Promise<void>;

export function SetTaskGroupBy(arg1:string):Promise<void>;

export function SetTaskPreset(arg1:string):Promise<void>;

export function SetTaskSidebarCollapsed(arg1:boolean):Promise<void>;

export function SetTaskSidebarWidth(arg1:number):Promise<void>;

export function SetTerminalTheme(arg1:string):Promise<void>;

export function SetUpdateGHProxyURL(arg1:string):Promise<void>;

export function SetUplinkPaused(arg1:boolean):Promise<void>;

export function SetWebglRendererEnabled(arg1:boolean):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function SignOutOtherRelaySessions():Promise<main.SignOutOthersResult>;

export function StartDownload():Promise<void>;
