// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastCommandFinished(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BroadcastCommandFinished'](arg1, arg2, arg3, arg4);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function CreatePairingToken() {
  return window['go']['main']['App']['CreatePairingToken']();
}

export function ExportDiagnostics(arg1) {
  return window['go']['main']['App']['ExportDiagnostics'](arg1);
}

export function FetchRelayMe() {
  return window['go']['main']['App']['FetchRelayMe']();
}

export function GetAutoCheckUpdates() {
  return window['go']['main']['App']['GetAutoCheckUpdates']();
}

export function GetClipboardPastePayload() {
  return window['go']['main']['App']['GetClipboardPastePayload']();
}

export function GetCommandNotifyThresholdSeconds() {
  return window['go']['main']['App']['GetCommandNotifyThresholdSeconds']();
}

export function GetDefaultShell() {
  return window['go']['main']['App']['GetDefaultShell']();
}

export function GetDiagnostics(arg1) {
  return window['go']['main']['App']['GetDiagnostics'](arg1);
}

export function GetEndpoint() {
  return window['go']['main']['App']['GetEndpoint']();
}

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetLocalePreference() {
  return window['go']['main']['App']['GetLocalePreference']();
}

export function GetLogPreview() {
  return window['go']['main']['App']['GetLogPreview']();
}

export function GetLoggingConfig() {
  return window['go']['main']['App']['GetLoggingConfig']();
}

export function GetNotificationsEnabled() {
  return window['go']['main']['App']['GetNotificationsEnabled']();
}

export function GetPluginConfig() {
  return window['go']['main']['App']['GetPluginConfig']();
}

export function GetQuickTemplates() {
  return window['go']['main']['App']['GetQuickTemplates']();
}

export function GetRelayConfig() {
  return window['go']['main']['App']['GetRelayConfig']();
}

export function GetShellIntegrationEnabled() {
  return window['go']['main']['App']['GetShellIntegrationEnabled']();
}

export function GetTaskPreset() {
  return window['go']['main']['App']['GetTaskPreset']();
}

export function GetTaskSidebarCollapsed() {
  return window['go']['main']['App']['GetTaskSidebarCollapsed']();
}

export function GetTerminalTheme() {
  return window['go']['main']['App']['GetTerminalTheme']();
}

export function GetUpdateGHProxyURL() {
  return window['go']['main']['App']['GetUpdateGHProxyURL']();
}

export function GetUpdateState() {
  return window['go']['main']['App']['GetUpdateState']();
}

export function GetUserHomeDir() {
  return window['go']['main']['App']['GetUserHomeDir']();
}

export function GetWebglRendererEnabled() {
  return window['go']['main']['App']['GetWebglRendererEnabled']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListShells() {
  return window['go']['main']['App']['ListShells']();
}

export function MarkSessionsSeen(arg1, arg2) {
  return window['go']['main']['App']['MarkSessionsSeen'](arg1, arg2);
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function PickLogFilePath() {
  return window['go']['main']['App']['PickLogFilePath']();
}

export function SetAutoCheckUpdates(arg1) {
  return window['go']['main']['App']['SetAutoCheckUpdates'](arg1);
}

export function SetCommandNotifyThresholdSeconds(arg1) {
  return window['go']['main']['App']['SetCommandNotifyThresholdSeconds'](arg1);
}

export function SetDefaultShell(arg1) {
  return window['go']['main']['App']['SetDefaultShell'](arg1);
}

export function SetLocalePreference(arg1) {
  return window['go']['main']['App']['SetLocalePreference'](arg1);
}

export function SetLoggingConfig(arg1) {
  return window['go']['main']['App']['SetLoggingConfig'](arg1);
}

export function SetNotificationsEnabled(arg1) {
  return window['go']['main']['App']['SetNotificationsEnabled'](arg1);
}

export function SetPluginConfig(arg1) {
  return window['go']['main']['App']['SetPluginConfig'](arg1);
}

export function SetQuickTemplates(arg1) {
  return window['go']['main']['App']['SetQuickTemplates'](arg1);
}

export function SetRelayConfig(arg1) {
  return window['go']['main']['App']['SetRelayConfig'](arg1);
}

export function SetShellIntegrationEnabled(arg1) {
  return window['go']['main']['App']['SetShellIntegrationEnabled'](arg1);
}

export function SetTaskPreset(arg1) {
  return window['go']['main']['App']['SetTaskPreset'](arg1);
}

export function SetTaskSidebarCollapsed(arg1) {
  return window['go']['main']['App']['SetTaskSidebarCollapsed'](arg1);
}

export function SetTerminalTheme(arg1) {
  return window['go']['main']['App']['SetTerminalTheme'](arg1);
}

export function SetUpdateGHProxyURL(arg1) {
  return window['go']['main']['App']['SetUpdateGHProxyURL'](arg1);
}

export function SetUplinkPaused(arg1) {
  return window['go']['main']['App']['SetUplinkPaused'](arg1);
}

export function SetWebglRendererEnabled(arg1) {
  return window['go']['main']['App']['SetWebglRendererEnabled'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartDownload() {
  return window['go']['main']['App']['StartDownload']();
}
