// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function GetAutoCheckUpdates() {
  return window['go']['main']['App']['GetAutoCheckUpdates']();
}

export function GetEndpoint() {
  return window['go']['main']['App']['GetEndpoint']();
}

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetRelayConfig() {
  return window['go']['main']['App']['GetRelayConfig']();
}

export function GetUpdateState() {
  return window['go']['main']['App']['GetUpdateState']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListShells() {
  return window['go']['main']['App']['ListShells']();
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function SetAutoCheckUpdates(arg1) {
  return window['go']['main']['App']['SetAutoCheckUpdates'](arg1);
}

export function SetRelayConfig(arg1) {
  return window['go']['main']['App']['SetRelayConfig'](arg1);
}

export function SetUplinkPaused(arg1) {
  return window['go']['main']['App']['SetUplinkPaused'](arg1);
}

export function FetchRelayMe() {
  return window['go']['main']['App']['FetchRelayMe']();
}

export function StartDownload() {
  return window['go']['main']['App']['StartDownload']();
}
