// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['main']['PluginFS']['CreateFile'](arg1);
}

export function FileMeta(arg1) {
  return window['go']['main']['PluginFS']['FileMeta'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['PluginFS']['ListDir'](arg1);
}

export function Mkdir(arg1) {
  return window['go']['main']['PluginFS']['Mkdir'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['PluginFS']['OpenExternal'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['PluginFS']['ReadFile'](arg1, arg2);
}

export function Remove(arg1, arg2) {
  return window['go']['main']['PluginFS']['Remove'](arg1, arg2);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['PluginFS']['Rename'](arg1, arg2);
}

export function RevealInOS(arg1) {
  return window['go']['main']['PluginFS']['RevealInOS'](arg1);
}

export function Trash(arg1) {
  return window['go']['main']['PluginFS']['Trash'](arg1);
}

export function UnwatchDir(arg1) {
  return window['go']['main']['PluginFS']['UnwatchDir'](arg1);
}

export function WatchDir(arg1) {
  return window['go']['main']['PluginFS']['WatchDir'](arg1);
}

export function WriteFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['PluginFS']['WriteFile'](arg1, arg2, arg3, arg4);
}
