// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string):Promise<main.FileMetaInfo>;

export function FileMeta(arg1:string):Promise<main.FileMetaInfo>;

export function ListDir(arg1:string):Promise<Array<main.DirEntry>>;

export function Mkdir(arg1:string):Promise<main.FileMetaInfo>;

export function OpenExternal(arg1:string):Promise<void>;

export function ReadFile(arg1:string,arg2:number):Promise<main.FileContent>;

export function Remove(arg1:string,arg2:boolean):Promise<void>;

export function Rename(arg1:string,arg2:string):Promise<main.FileMetaInfo>;

export function RevealInOS(arg1:string):Promise<void>;

export function Trash(arg1:string):Promise<void>;

export function UnwatchDir(arg1:number):Promise<void>;

export function WatchDir(arg1:string):Promise<number>;

export function WriteFile(arg1:string,arg2:Array<number>,arg3:number,arg4:boolean):Promise<main.FileMetaInfo>;
