// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileMeta(arg1) {
  return window['go']['main']['PluginFS']['FileMeta'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['PluginFS']['ListDir'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['PluginFS']['OpenExternal'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['PluginFS']['ReadFile'](arg1, arg2);
}

export function RevealInOS(arg1) {
  return window['go']['main']['PluginFS']['RevealInOS'](arg1);
}
